version: 2
jobs:
  build:
    working_directory: ~/brave-kt
    docker:
    - image: openjdk:8-jdk

    steps:
    - checkout

    - restore_cache:
        keys:
        - v1-build-dependencies-{{ checksum "settings.gradle.kts" }}-{{ checksum "build.gradle.kts" }}-{{ checksum "gradle.properties" }}

    - run:
        name: ktlintCheck and build
        command: ./gradlew ktlintCheck build

    - save_cache:
        paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper
        key: v1-build-dependencies-{{ checksum "settings.gradle.kts" }}-{{ checksum "build.gradle.kts" }}-{{ checksum "gradle.properties" }}

    - store_artifacts:
        path: ./build/libs/

  test:
    working_directory: ~/brave-kt
    docker:
      - image: openjdk:8-jdk

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-test-dependencies-{{ checksum "settings.gradle.kts" }}-{{ checksum "build.gradle.kts" }}-{{ checksum "gradle.properties" }}

      - run:
          name: Test
          command: ./gradlew test jacocoTestReport --no-daemon --max-workers 2

      - store_test_results:
          path: build/test-results

      - store_artifacts:
          path: build/test-results

      - store_artifacts:
          path: build/reports

      - save_cache:
          paths:
          - ~/.gradle/caches
          - ~/.gradle/wrapper
          key: v1-test-dependencies-{{ checksum "settings.gradle.kts" }}-{{ checksum "build.gradle.kts" }}-{{ checksum "gradle.properties" }}

workflows:
  version: 2
  build_and_test:
    jobs:
    - build
    - test